### PR TITLE
removed volta

### PR DESCRIPTION
**Pull request by kaareal**
If you already have volta installed, before you have bedrock installed, then you will end up with a node version 12. 
Which doesnt work out on m1 chipset. 

This stops volta to install a old version node version. Instead put package.engines https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines which should yield some warnings if the old version of node is installed (but shouldnt fail)

~also removed .babelrc because there is no babel installed, to use it.~ Was used for jest

### CODE REVIEW

**Review by beatlevic — APPROVED** [review]
LGTM

**Comment by andrewplummer** [comment]
@kaareal why don't we just bump the node version instead? Does volta respect the `engines` directive?

**Comment by kaareal** [comment]
I think thats what this PR does, it dumps the node version.

And removes volta, as volta i assume is not an requirement for bedrock cli

**Comment by andrewplummer** [comment]
it's not but if it's installed we would like to ensure a minimum version so why not keep it?

**Comment by kaareal** [comment]
volta doesnt ensure a minimum version, it will install the version specified, which is what caused the original problem.
I think its better if uses the version of node you have installed and then warn via npm if the engine doesn't match.

**Comment by andrewplummer** [comment]
but what will happen if you're coming from a new machine and ONLY installed volta?

**Comment by kaareal** [comment]
node 12 would be installed
see the description at the top :)

**Comment by andrewplummer** [comment]
yes but you're saying that's a problem for M1+ chips right?

**Comment by kaareal** [comment]
i guess thats correct, but why install force install an very old version node, instead of using the one the user has installed

**Comment by andrewplummer** [comment]
I'm saying to update the volta field as well to 16 to let them install a new version

**Comment by kaareal** [comment]
why would want to maintain that? 
I really dont see why you want to force a specify version of node to be installed for users that have volta installed.
but sure, say the word and i will revert it.

**Comment by andrewplummer** [comment]
ok after discussion I'm cool to remove... I still don't quite get the issue but either way locking down to a specific version as we do in volta shouldn't be required I suppose

**Pull request merged**
